services:
  mirofish:
    image: ghcr.io/666ghj/mirofish:latest
    # Mirror image (use this if the above pull is slow)
    # image: ghcr.nju.edu.cn/666ghj/mirofish:latest
    container_name: mirofish2
    env_file:
      - .env
    ports:
      - "3001:3000"
      - "5001:5001"
    restart: no
    environment:
      - UV_LINK_MODE=copy
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      - /app/frontend/node_modules
      - /app/node_modules
      - /app/backend/.venv